title: Josh De Freitas
logo: /assets/img/dp_edit.jpg
email: joshdefreitas@gmail.com
description: Digital Transformation Analyst
show_downloads: false
google_analytics: G-ZLK2GHB055
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/joshdefreitas
  - name: Certificates
    icon: <i class="fa-solid fa-trophy"></i>
    link: https://joshdefreitas.info/certificates
  - name: Projects
    icon: <i class="fa-regular fa-folder-open"></i>
    link: https://joshdefreitas.info/projects  
  - name: Personal Blog
    icon: <i class="fa-solid fa-pencil"></i>
    link: https://blog.joshdefreitas
  - name: Photography
    icon: <i class="fa-solid fa-camera"></i>
    link: https://photos.joshdefreitas.info


# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
